// GENERATED by tools/gen_faceless.py — do not edit by hand.
// Edit <project>/work/storyboard.json and re-run with --from-storyboard.
import React from 'react';
import { StoryboardVideo, type Scene } from '../../lib/storyboard';

export const compositionConfig = { id: 'SrcCodeReviewGraphStopBurningTokens', durationInSeconds: 148.333, fps: 30, width: 1920, height: 1080 };

const SCENES = ([
  {
    "type": "title",
    "narration": "Stop burning tokens on massive codebases and start performing much smarter automated code reviews.",
    "eyebrow": "AI Dev Tools",
    "title": "Code Review Graph",
    "subtitle": "Stop burning tokens. Start reviewing smarter.",
    "dur": 218,
    "audio": "projects/studio/narration/00.mp3"
  },
  {
    "type": "statement",
    "narration": "Code Review Graph provides a local-first code intelligence graph for your MCP and CLI tools.",
    "eyebrow": "Overview",
    "text": "Local-First Code Intelligence for MCP & CLI",
    "dur": 220,
    "audio": "projects/studio/narration/01.mp3"
  },
  {
    "type": "repo_scroll",
    "narration": "With nearly twenty-five thousand stars, the repository features comprehensive documentation for various AI agents.",
    "eyebrow": "GitHub Repository",
    "repo": {
      "owner": "tirth8205",
      "name": "code-review-graph",
      "url": "https://github.com/tirth8205/code-review-graph",
      "stars": 24929,
      "description": "Local-first code intelligence graph for MCP and CLI. Builds a persistent map of your codebase so AI coding tools read only what matters, wit",
      "topics": [
        "Python",
        "ai-coding",
        "claude",
        "claude-code",
        "code-review",
        "graphrag"
      ],
      "files": [
        "AGENTS.md",
        "CHANGELOG.md",
        "CLAUDE.md",
        "CODE_OF_CONDUCT.md",
        "CONTRIBUTING.md",
        "GEMINI.md",
        "LICENSE",
        "README.hi-IN.md",
        "README.ja-JP.md",
        "README.ko-KR.md",
        "README.md",
        "README.zh-CN.md"
      ],
      "readme": [
        "Local-first code intelligence graph for MCP and CLI. Builds a persistent map of your",
        "codebase so AI coding tools read only what matters, with benchmarked context reductions",
        "## Features",
        "- Quick Start",
        "- How It Works",
        "- Blast-radius analysis",
        "- Incremental updates in < 2 seconds",
        "- The monorepo problem, solved",
        "- Broad language coverage + Jupyter notebooks",
        "## Highlights",
        "- uses: actions/checkout@v7",
        "- uses: tirth8205/code-review-graph@v2.3.6",
        "## Built with",
        "Python, ai-coding, claude, claude-code, code-review, graphrag, incremental, knowledge-graph"
      ]
    },
    "dur": 257,
    "audio": "projects/studio/narration/02.mp3"
  },
  {
    "type": "features",
    "narration": "It constructs a persistent codebase map so your AI coding tools read only what matters.",
    "eyebrow": "How It Works",
    "items": [
      {
        "label": "Persistent Code Map"
      },
      {
        "label": "Filtered Context"
      }
    ],
    "dur": 203,
    "audio": "projects/studio/narration/03.mp3"
  },
  {
    "type": "statement",
    "narration": "Achieve benchmarked context reductions while running detailed code reviews across massive, complex monorepos.",
    "eyebrow": "Performance",
    "text": "Benchmarked Context Reduction for Large Repos",
    "dur": 246,
    "audio": "projects/studio/narration/04.mp3"
  },
  {
    "type": "bullets",
    "narration": "Run deep blast-radius analysis to instantly uncover how every change impacts surrounding dependencies.",
    "eyebrow": "Analysis Capabilities",
    "points": [
      "Blast-radius analysis",
      "Monorepo problem, solved"
    ],
    "title": "Deep Code Insights",
    "dur": 229,
    "audio": "projects/studio/narration/05.mp3"
  },
  {
    "type": "statement",
    "narration": "Keep your codebase context perpetually updated without spending time re-indexing the entire repository again.",
    "eyebrow": "Speed",
    "text": "Incremental Updates in Under 2 Seconds",
    "dur": 238,
    "audio": "projects/studio/narration/06.mp3"
  },
  {
    "type": "code",
    "narration": "Start quickly by installing the Python package via pip or pipx straight from your terminal.",
    "eyebrow": "Installation",
    "lines": [
      "pip install code-review-graph",
      "code-review-graph install",
      "code-review-graph build"
    ],
    "filename": "terminal",
    "dur": 203,
    "audio": "projects/studio/narration/07.mp3"
  },
  {
    "type": "steps",
    "narration": "Run the setup command to automatically detect and configure all your supported developer platforms.",
    "eyebrow": "Quick Start",
    "steps": [
      "Install package via pip",
      "Auto-detect platform settings",
      "Build persistent codebase map"
    ],
    "dur": 214,
    "audio": "projects/studio/narration/08.mp3"
  },
  {
    "type": "statement",
    "narration": "Process fast incremental updates in under two seconds whenever files change in your active workspace.",
    "eyebrow": "Efficiency",
    "text": "Fast <2 Second Workspace Syncing",
    "dur": 225,
    "audio": "projects/studio/narration/09.mp3"
  },
  {
    "type": "features",
    "narration": "Enjoy broad language coverage alongside complete support for analyzing interactive Jupyter notebooks seamlessly.",
    "eyebrow": "Broad Compatibility",
    "items": [
      {
        "label": "Broad Language Support"
      },
      {
        "label": "Jupyter Notebooks"
      }
    ],
    "dur": 241,
    "audio": "projects/studio/narration/10.mp3"
  },
  {
    "type": "statement",
    "narration": "Solve the monorepo context overflow problem using state of the art GraphRAG knowledge graphs.",
    "eyebrow": "Architecture",
    "text": "Powered by GraphRAG Knowledge Graphs",
    "dur": 221,
    "audio": "projects/studio/narration/11.mp3"
  },
  {
    "type": "bullets",
    "narration": "Power up tools like Claude Code and Gemini agents with local graph-based codebase intelligence.",
    "eyebrow": "Ecosystem Integrations",
    "points": [
      "Claude & Claude Code",
      "Gemini workflows",
      "Custom agent configs"
    ],
    "title": "Supported AI Agents",
    "dur": 216,
    "audio": "projects/studio/narration/12.mp3"
  },
  {
    "type": "code",
    "narration": "Integrate directly into your automated workflows using official GitHub Actions steps and standard checkout.",
    "eyebrow": "CI Automation",
    "lines": [
      "uses: actions/checkout@v7",
      "uses: tirth8205/code-review-graph@v2.3.6"
    ],
    "filename": "workflow.yml",
    "dur": 231,
    "audio": "projects/studio/narration/13.mp3"
  },
  {
    "type": "statement",
    "narration": "Maintain complete data privacy with local-first processing that keeps sensitive source code fully secure.",
    "eyebrow": "Security",
    "text": "Local-First Architecture for Code Privacy",
    "dur": 231,
    "audio": "projects/studio/narration/14.mp3"
  },
  {
    "type": "features",
    "narration": "Streamline developer workflows, slash token consumption, and make code reviews significantly faster than ever.",
    "eyebrow": "Core Benefits",
    "items": [
      {
        "label": "Slash Token Usage"
      },
      {
        "label": "Smarter Reviews"
      }
    ],
    "dur": 238,
    "audio": "projects/studio/narration/15.mp3"
  },
  {
    "type": "statement",
    "narration": "Give your AI coding assistants exact codebase context without wasting expensive tokens or time.",
    "eyebrow": "Summary",
    "text": "Precise Context Without Wasted Resources",
    "dur": 223,
    "audio": "projects/studio/narration/16.mp3"
  },
  {
    "type": "bullets",
    "narration": "Build a persistent local map, evaluate impact radius, and optimize your developer toolchain today.",
    "eyebrow": "Key Takeaways",
    "points": [
      "Persistent graph indexing",
      "Instant blast-radius analysis",
      "Seamless CLI & MCP setup"
    ],
    "title": "Why Code Review Graph",
    "dur": 223,
    "audio": "projects/studio/narration/17.mp3"
  },
  {
    "type": "statement",
    "narration": "Transform how your AI dev tools inspect complex codebases starting right now.",
    "eyebrow": "Next Steps",
    "text": "Upgrade Your Code Review Workflow",
    "dur": 191,
    "audio": "projects/studio/narration/18.mp3"
  },
  {
    "type": "cta",
    "narration": "Visit the GitHub repository today to build your graph and start reviewing smarter.",
    "title": "Try Code Review Graph",
    "sub": "github.com/tirth8205/code-review-graph",
    "dur": 182,
    "audio": "projects/studio/narration/19.mp3"
  }
]) as unknown as Scene[];

const SrcCodeReviewGraphStopBurningTokens: React.FC = () => (
  <StoryboardVideo scenes={SCENES} width={1920} height={1080} captions={true} templateId={'midnight'} />
);
export default SrcCodeReviewGraphStopBurningTokens;
