// GENERATED by tools/gen_faceless.py — do not edit by hand.
// Edit <project>/work/storyboard.json and re-run with --from-storyboard.
import React from 'react';
import { StoryboardVideo, type Scene } from '../../lib/storyboard';

export const compositionConfig = { id: 'SrcClaudeYoutubeEditor', durationInSeconds: 29.067, fps: 30, width: 1920, height: 1080 };

const SCENES = ([
  {
    "type": "title",
    "dur": 110,
    "eyebrow": "open-source · github",
    "title": "claude-youtube-editor",
    "subtitle": "claude-youtube-editor Record the talking head. Claude Code d…",
    "narration": "claude-youtube-editor. claude-youtube-editor Record the talking head. Claude Code d…"
  },
  {
    "type": "statement",
    "dur": 140,
    "eyebrow": "overview",
    "text": "claude-youtube-editor Record the talking head. Claude Code does the rest.",
    "narration": "claude-youtube-editor Record the talking head. Claude Code does the rest."
  },
  {
    "type": "features",
    "dur": 192,
    "eyebrow": "highlights",
    "items": [
      {
        "label": "The six steps"
      },
      {
        "label": "What you record vs what it builds"
      },
      {
        "label": "Quickstart"
      }
    ],
    "narration": "Highlights: The six steps; What you record vs what it builds; Quickstart."
  },
  {
    "type": "code",
    "dur": 150,
    "eyebrow": "get started",
    "filename": "terminal",
    "lines": [
      "cd claude-youtube-editor",
      "python -m venv venv",
      "cd remotion && npm run studio"
    ],
    "narration": "Getting started takes a few commands."
  },
  {
    "type": "bullets",
    "dur": 190,
    "eyebrow": "key points",
    "title": "What matters",
    "points": [
      "Transitions — a proper transition library between beats",
      "Effects — zoom/punch-in, highlight, spotlight passes",
      "Filters — grade/look presets that respect the brand contract",
      "No script writer. This edits video; it doesn't write it.",
      "No footage. The example's shots ship, its raw recording doesn't videos/ starts empty."
    ],
    "narration": "The key points at a glance."
  },
  {
    "type": "cta",
    "dur": 90,
    "title": "Star it on GitHub",
    "sub": "https://github.com/Sravankumarraju/claude-youtube-editor",
    "narration": "Star it on GitHub."
  }
]) as unknown as Scene[];

const SrcClaudeYoutubeEditor: React.FC = () => (
  <StoryboardVideo scenes={SCENES} width={1920} height={1080} captions={true} />
);
export default SrcClaudeYoutubeEditor;
