// GENERATED by tools/gen_faceless.py — do not edit by hand.
// Edit <project>/work/storyboard.json and re-run with --from-storyboard.
import React from 'react';
import { StoryboardVideo, type Scene } from '../../lib/storyboard';

export const compositionConfig = { id: 'SrcLast30daysSkill', durationInSeconds: 45.467, fps: 30, width: 1920, height: 1080 };

const SCENES = ([
  {
    "type": "title",
    "dur": 211,
    "eyebrow": "open-source · github",
    "title": "last30days-skill",
    "subtitle": "AI agent skill that researches any topic across Reddit, X, Y…",
    "narration": "last30days-skill. AI agent skill that researches any topic across Reddit, X, Y…",
    "audio": "projects/studio/narration/00.mp3"
  },
  {
    "type": "statement",
    "dur": 322,
    "eyebrow": "overview",
    "text": "AI agent skill that researches any topic across Reddit, X, YouTube, HN, Polymarket, and the web - then synthesizes a grounded summary",
    "narration": "AI agent skill that researches any topic across Reddit, X, YouTube, HN, Polymarket, and the web - then synthesizes a grounded summary",
    "audio": "projects/studio/narration/01.mp3"
  },
  {
    "type": "features",
    "dur": 221,
    "eyebrow": "highlights",
    "items": [
      {
        "label": "Why this exists"
      },
      {
        "label": "Sources, scored by the people"
      },
      {
        "label": "What people actually use it for"
      }
    ],
    "narration": "Highlights: Why this exists; Sources, scored by the people; What people actually use it for.",
    "audio": "projects/studio/narration/02.mp3"
  },
  {
    "type": "steps",
    "dur": 231,
    "eyebrow": "built with",
    "steps": [
      "Python",
      "ai-prompts",
      "ai-skill",
      "bluesky",
      "claude",
      "claude-code"
    ],
    "narration": "Built with Python, ai-prompts, ai-skill, bluesky, claude, claude-code.",
    "audio": "projects/studio/narration/03.mp3"
  },
  {
    "type": "code",
    "dur": 150,
    "eyebrow": "get started",
    "filename": "terminal",
    "lines": [
      "npx skills add mvanhorn/last30days-skill -g",
      "npx skills add mvanhorn/last30days-skill -g -a claude-code",
      "npx skills add mvanhorn/last30days-skill -g",
      "npx skills add mvanhorn/last30days-skill -g -a codex",
      "npx skills add mvanhorn/last30days-skill -g -a cursor",
      "npx skills add mvanhorn/last30days-skill -g -a gemini-cli"
    ],
    "narration": "Getting started takes a few commands.",
    "audio": "projects/studio/narration/04.mp3"
  },
  {
    "type": "bullets",
    "dur": 138,
    "eyebrow": "key points",
    "title": "What matters",
    "points": [
      "macOS Apple Silicon: last30days-pp-mcp-darwin-arm64.mcpb",
      "macOS Intel: last30days-pp-mcp-darwin-amd64.mcpb",
      "Linux x8664: last30days-pp-mcp-linux-amd64.mcpb"
    ],
    "narration": "The key points at a glance.",
    "audio": "projects/studio/narration/05.mp3"
  },
  {
    "type": "cta",
    "dur": 91,
    "title": "Star it on GitHub",
    "sub": "https://github.com/mvanhorn/last30days-skill",
    "narration": "Star it on GitHub.",
    "audio": "projects/studio/narration/06.mp3"
  }
]) as unknown as Scene[];

const SrcLast30daysSkill: React.FC = () => (
  <StoryboardVideo scenes={SCENES} width={1920} height={1080} captions={true} templateId={'brand'} />
);
export default SrcLast30daysSkill;
