// GENERATED by tools/gen_faceless.py — do not edit by hand.
// Edit <project>/work/storyboard.json and re-run with --from-storyboard.
import React from 'react';
import { StoryboardVideo, type Scene } from '../../lib/storyboard';

export const compositionConfig = { id: 'SrcStopBurningTokensWithCodeReviewG', durationInSeconds: 142.9, fps: 30, width: 1920, height: 1080 };

const SCENES = ([
  {
    "type": "title",
    "narration": "Stop burning through hundreds of thousands of AI tokens every single time you perform a code review. When you feed an entire repository into an LLM context window, you waste money, slow down response times, and dilute the model's focus on the actual changes that matter.",
    "eyebrow": "GitHub Spotlight",
    "title": "code-review-graph",
    "subtitle": "Stop burning tokens. Start reviewing smarter.",
    "dur": 590,
    "audio": "projects/studio/narration/00.mp3"
  },
  {
    "type": "statement",
    "narration": "Meet code-review-graph, a local-first code intelligence graph built specifically for MCP and CLI workflows. It constructs a persistent map of your codebase, ensuring your AI coding tools read only what is relevant for benchmarked context reduction.",
    "eyebrow": "The Solution",
    "text": "Local-first code intelligence graph for MCP and CLI.",
    "dur": 535,
    "audio": "projects/studio/narration/01.mp3"
  },
  {
    "type": "repo_scroll",
    "narration": "Taking a look at the official GitHub repository—which has accumulated nearly 25,000 stars—the project structure is clearly organized. Right in the root directory, you will find dedicated configuration files like AGENTS.md, CLAUDE.md, and GEMINI.md, alongside international documentation in Japanese, Korean, Hindi, and Chinese.",
    "eyebrow": "GitHub Repository",
    "repo": {
      "owner": "tirth8205",
      "name": "code-review-graph",
      "url": "https://github.com/tirth8205/code-review-graph",
      "stars": 24929,
      "description": "Local-first code intelligence graph for MCP and CLI. Builds a persistent map of your codebase so AI coding tools read only what matters, wit",
      "topics": [
        "Python",
        "ai-coding",
        "claude",
        "claude-code",
        "code-review",
        "graphrag"
      ],
      "files": [
        "AGENTS.md",
        "CHANGELOG.md",
        "CLAUDE.md",
        "CODE_OF_CONDUCT.md",
        "CONTRIBUTING.md",
        "GEMINI.md",
        "LICENSE",
        "README.hi-IN.md",
        "README.ja-JP.md",
        "README.ko-KR.md",
        "README.md",
        "README.zh-CN.md"
      ],
      "readme": [
        "Local-first code intelligence graph for MCP and CLI. Builds a persistent map of your",
        "codebase so AI coding tools read only what matters, with benchmarked context reductions",
        "## Features",
        "- Quick Start",
        "- How It Works",
        "- Blast-radius analysis",
        "- Incremental updates in < 2 seconds",
        "- The monorepo problem, solved",
        "- Broad language coverage + Jupyter notebooks",
        "## Highlights",
        "- uses: actions/checkout@v7",
        "- uses: tirth8205/code-review-graph@v2.3.6",
        "## Built with",
        "Python, ai-coding, claude, claude-code, code-review, graphrag, incremental, knowledge-graph"
      ]
    },
    "dur": 709,
    "audio": "projects/studio/narration/02.mp3"
  },
  {
    "type": "features",
    "narration": "Why is this approach so effective? It solves the monorepo problem using GraphRAG to run blast-radius analysis across dependencies. It supports broad language coverage including Jupyter notebooks, and processes incremental updates in less than two seconds.",
    "eyebrow": "Key Capabilities",
    "items": [
      {
        "label": "Blast-radius analysis"
      },
      {
        "label": "Incremental updates in < 2s"
      },
      {
        "label": "Monorepo support"
      },
      {
        "label": "Jupyter notebook coverage"
      }
    ],
    "dur": 536,
    "audio": "projects/studio/narration/03.mp3"
  },
  {
    "type": "code",
    "narration": "Getting started in your terminal takes just three commands. Install the package using pip or pipx, execute install to auto-detect and configure all supported platforms, and then run build to parse your codebase into a structured graph.",
    "eyebrow": "Quick Start",
    "lines": [
      "pip install code-review-graph                     # or: pipx install code-review-graph",
      "code-review-graph install          # auto-detects and configures all supported platforms",
      "code-review-graph build            # parse your codebase"
    ],
    "filename": "terminal",
    "dur": 487,
    "audio": "projects/studio/narration/04.mp3"
  },
  {
    "type": "steps",
    "narration": "Once your graph is generated, AI tools read only targeted context instead of full files. When a function updates, the system instantly identifies the affected blast radius, keeping token usage minimal and context precise.",
    "eyebrow": "How It Works",
    "steps": [
      "Build persistent codebase graph",
      "Detect blast radius of changes",
      "Pass focused context to AI tools"
    ],
    "dur": 482,
    "audio": "projects/studio/narration/05.mp3"
  },
  {
    "type": "bullets",
    "narration": "You can also bring these context reductions directly into your continuous integration pipeline. By pairing standard checkout actions with version 2.3.6 of code-review-graph, your automated pull request reviews run efficiently.",
    "eyebrow": "Automation",
    "points": [
      "uses: actions/checkout@v7",
      "uses: tirth8205/code-review-graph@v2.3.6"
    ],
    "title": "CI/CD Integration",
    "dur": 469,
    "audio": "projects/studio/narration/06.mp3"
  },
  {
    "type": "cta",
    "narration": "Stop burning tokens and start reviewing smarter. Whether you use Claude, Claude Code, or Python-based AI workflows, code-review-graph gives your AI tools the exact context they need. Check out the link below and try it today.",
    "title": "Start Reviewing Smarter",
    "sub": "github.com/tirth8205/code-review-graph",
    "dur": 479,
    "audio": "projects/studio/narration/07.mp3"
  }
]) as unknown as Scene[];

const SrcStopBurningTokensWithCodeReviewG: React.FC = () => (
  <StoryboardVideo scenes={SCENES} width={1920} height={1080} captions={true} templateId={'midnight'} />
);
export default SrcStopBurningTokensWithCodeReviewG;
