// GENERATED by tools/gen_package.py — thumbnail shot.
import React from 'react';
import { ThumbnailCard, type ThumbProps } from '../../lib/thumbnail';

export const compositionConfig = { id: 'ThumbCodeReviewGraph1', durationInSeconds: 1, fps: 30, width: 1280, height: 720 };

const PROPS = ({"overlay": "SMARTER AI CONTEXT", "name": "code-review-graph", "owner": "tirth8205", "stars": 24929, "templateId": "midnight", "variant": 1}) as ThumbProps;
const ThumbCodeReviewGraph1: React.FC = () => <ThumbnailCard {...PROPS} />;
export default ThumbCodeReviewGraph1;
