// GENERATED by tools/gen_package.py — thumbnail shot.
import React from 'react';
import { ThumbnailCard, type ThumbProps } from '../../lib/thumbnail';

export const compositionConfig = { id: 'ThumbCodeReviewGraph0', durationInSeconds: 1, fps: 30, width: 1280, height: 720 };

const PROPS = ({"overlay": "STOP WASTING TOKENS", "name": "code-review-graph", "owner": "tirth8205", "stars": 24929, "templateId": "midnight", "variant": 0}) as ThumbProps;
const ThumbCodeReviewGraph0: React.FC = () => <ThumbnailCard {...PROPS} />;
export default ThumbCodeReviewGraph0;
