// GENERATED by tools/gen_faceless.py — do not edit by hand.
// Edit <project>/work/storyboard.json and re-run with --from-storyboard.
import React from 'react';
import { StoryboardVideo, type Scene } from '../../lib/storyboard';

export const compositionConfig = { id: 'SrcStopBurningAITokensWithCodeRevie', durationInSeconds: 39.2, fps: 30, width: 1920, height: 1080 };

const SCENES = ([
  {
    "type": "title",
    "narration": "Stop burning AI tokens on massive codebases.",
    "eyebrow": "24K+ Stars on GitHub",
    "title": "code-review-graph",
    "subtitle": "Stop burning tokens. Start reviewing smarter.",
    "dur": 211,
    "audio": "projects/studio/narration/00.mp3"
  },
  {
    "type": "statement",
    "narration": "code-review-graph builds a persistent map of your repository so AI coding tools read only what matters.",
    "eyebrow": "Smart Context",
    "text": "Local-first code intelligence graph for MCP and CLI",
    "dur": 322,
    "audio": "projects/studio/narration/01.mp3"
  },
  {
    "type": "features",
    "narration": "It runs incremental updates in under two seconds, delivering blast-radius analysis and full monorepo support.",
    "eyebrow": "Core Features",
    "items": [
      {
        "label": "Blast-radius analysis"
      },
      {
        "label": "Updates in < 2 seconds"
      },
      {
        "label": "Monorepo & Jupyter support"
      }
    ],
    "dur": 245,
    "audio": "projects/studio/narration/02.mp3"
  },
  {
    "type": "code",
    "narration": "Install it with pip, configure supported platforms, and build your local graph with three simple commands.",
    "eyebrow": "Quick Start",
    "lines": [
      "pip install code-review-graph",
      "code-review-graph install",
      "code-review-graph build"
    ],
    "filename": "terminal",
    "dur": 231,
    "audio": "projects/studio/narration/03.mp3"
  },
  {
    "type": "cta",
    "narration": "Check out code-review-graph on GitHub and start reviewing smarter today.",
    "title": "Review Smarter Today",
    "sub": "github.com/tirth8205/code-review-graph",
    "dur": 167,
    "audio": "projects/studio/narration/04.mp3"
  }
]) as unknown as Scene[];

const SrcStopBurningAITokensWithCodeRevie: React.FC = () => (
  <StoryboardVideo scenes={SCENES} width={1920} height={1080} captions={true} templateId={'midnight'} />
);
export default SrcStopBurningAITokensWithCodeRevie;
