#!/usr/bin/env python3
"""Stage 6 packaging — click-worthy title, description, and thumbnails for a video.

Reads the project's storyboard.json (+ source.json for grounding), asks Gemini for
packaging copy (3 title options, a description, and thumbnail concepts), then renders
each thumbnail with tools/gen_thumbnail.py (Gemini image / Nano Banana Pro). Writes
media/projects/<name>/packaging/ + packaging.json. No faces required (faceless channel).

Usage (repo root, venv python; needs GEMINI_API_KEY in .env):
    python tools/gen_package.py --project videos/studio --count 2
"""
from __future__ import annotations
import argparse
import json
import subprocess
import sys
from pathlib import Path

from textutil import strip_emoji
from gen_script import load_key, call_gemini, parse_json
from gen_faceless import build_repo_view, _pascal

REPO = Path(__file__).resolve().parent.parent
RE_DIR = REPO / "remotion"
PY = sys.executable
DEFAULT_MODEL = "gemini-flash-latest"

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
    except Exception:
        pass


def copy_prompt(sb: dict, src: dict, count: int) -> str:
    scenes = sb.get("scenes", [])
    hook = next((s.get("narration") for s in scenes if s.get("narration")), "")
    grounding = {
        "url": src.get("url"), "stars": src.get("stars"),
        "summary": src.get("summary"), "features": (src.get("features") or [])[:8],
        "tech_stack": (src.get("tech_stack") or [])[:8],
    }
    return f"""You are a YouTube packaging expert for a channel about GitHub projects and AI dev tools. \
Produce click-worthy packaging for the video below. Titles must create curiosity AND state a benefit — \
punchy, honest (no clickbait lies), <= 70 characters. Thumbnails need a SHORT 2-4 word punch that is huge \
and legible. Ground everything in the SOURCE — no invented numbers or features.

Return ONLY JSON (no fence):
{{
  "titles": ["3 distinct title options"],
  "description": "2-3 sentence YouTube description, ending with the repo URL",
  "thumbnails": [{{"overlay": "2-4 WORD punch", "concept": "one line describing the thumbnail image"}}]
}}
Give exactly {count} thumbnail objects, each a different angle (e.g. the problem, the payoff, the how).

SCRIPT TITLE: {sb.get('title')}
OPENING HOOK: {hook}
SOURCE (JSON):
{json.dumps(grounding, ensure_ascii=False, indent=2)}
"""


def emit_thumb_shot(slug: str, i: int, overlay: str, repo: dict, template_id: str) -> tuple[str, Path]:
    """Write a thin Remotion shot that renders <ThumbnailCard/> as a 1280x720 still."""
    comp_id = f"Thumb{slug}{i}"
    props = json.dumps({
        "overlay": overlay, "name": repo.get("name") or slug,
        "owner": repo.get("owner"), "stars": repo.get("stars"),
        "templateId": template_id, "variant": i,
    }, ensure_ascii=False)
    tsx = f"""// GENERATED by tools/gen_package.py — thumbnail shot.
import React from 'react';
import {{ ThumbnailCard, type ThumbProps }} from '../../lib/thumbnail';

export const compositionConfig = {{ id: '{comp_id}', durationInSeconds: 1, fps: 30, width: 1280, height: 720 }};

const PROPS = ({props}) as ThumbProps;
const {comp_id}: React.FC = () => <ThumbnailCard {{...PROPS}} />;
export default {comp_id};
"""
    out_dir = RE_DIR / "src" / "shots" / f"pkg-{slug.lower()}"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{comp_id}.tsx"
    path.write_text(tsx, encoding="utf-8")
    return comp_id, path


def png_to_jpg(png: Path, jpg: Path) -> None:
    try:
        from PIL import Image
        Image.open(png).convert("RGB").save(jpg, "JPEG", quality=88, optimize=True, progressive=True)
    except Exception:
        pass


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate title/description/thumbnails for a video.")
    ap.add_argument("--project", required=True, help="project dir, e.g. videos/studio")
    ap.add_argument("--count", type=int, default=2, help="number of thumbnails (1-3)")
    ap.add_argument("--model", default=DEFAULT_MODEL, help="Gemini text model for copy")
    ap.add_argument("--no-image", action="store_true", help="write copy only; skip thumbnail rendering")
    args = ap.parse_args()

    count = max(1, min(3, args.count))
    work = Path(args.project) / "work"
    sb_path = work / "storyboard.json"
    if not sb_path.exists():
        print(f"ERROR: {sb_path} not found. Generate a video first.", file=sys.stderr)
        return 1
    sb = json.loads(sb_path.read_text(encoding="utf-8"))
    src = {}
    src_path = work / "source.json"
    if src_path.exists():
        src = json.loads(src_path.read_text(encoding="utf-8"))

    name = Path(args.project).name
    pkg_dir = REPO / "media" / "projects" / name / "packaging"
    pkg_dir.mkdir(parents=True, exist_ok=True)
    repo_name = sb.get("title") or name
    repo = build_repo_view(src) or {"name": src.get("title") or name}
    template_id = sb.get("template") or "brand"
    slug = _pascal(src.get("title") or repo.get("name") or name)

    # 1) copy (titles + description + thumbnail concepts) via Gemini text
    try:
        key = load_key()
        raw = parse_json(call_gemini(key, args.model, copy_prompt(sb, src, count)))
    except Exception as e:  # noqa: BLE001
        print(f"PACKAGING FAILED (copy): {type(e).__name__}: {e}", file=sys.stderr)
        return 3
    titles = [strip_emoji(str(t).strip()) for t in (raw.get("titles") or []) if str(t).strip()][:3]
    description = strip_emoji(str(raw.get("description") or "").strip())
    concepts = raw.get("thumbnails") or []
    if not titles:
        titles = [repo_name]
    print(f"titles: {titles}")

    # 2) render thumbnails in Remotion (no image API): emit a shot per concept,
    #    register once, then render each as a still + a YouTube JPG.
    thumbs: list[dict] = []
    if not args.no_image:
        overlays = []
        for i in range(count):
            c = concepts[i] if i < len(concepts) else {}
            overlays.append(strip_emoji(str(c.get("overlay") or repo.get("name") or repo_name)[:36]))
        comps = [emit_thumb_shot(slug, i, ov, repo, template_id)[0] for i, ov in enumerate(overlays)]
        subprocess.run(["node", "scripts/gen-registry.mjs"], cwd=str(RE_DIR),
                       capture_output=True, text=True)
        print(f"  rendering {len(comps)} thumbnail(s): {', '.join(overlays)}")
        r = subprocess.run(["node", "scripts/render-still.mjs", str(pkg_dir), *comps],
                           cwd=str(RE_DIR), capture_output=True, text=True, encoding="utf-8", errors="replace")
        if r.returncode != 0:
            tail = (r.stderr or r.stdout or "").strip().splitlines()[-2:] or ["render failed"]
            print("  ! thumbnail render failed: " + " | ".join(tail), file=sys.stderr)
        for i, (comp, ov) in enumerate(zip(comps, overlays)):
            png = pkg_dir / f"{comp}.png"
            if png.exists():
                png_to_jpg(png, pkg_dir / f"{comp}.jpg")
                thumbs.append({"overlay": ov,
                               "file": f"projects/{name}/packaging/{comp}.png",
                               "jpg": f"projects/{name}/packaging/{comp}.jpg"})

    pkg = {"title": titles[0], "titles": titles, "description": description, "thumbnails": thumbs}
    (work / "packaging.json").write_text(json.dumps(pkg, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nOK  packaging: {len(titles)} titles, {len(thumbs)} thumbnail(s)")
    print(f"    -> {(work / 'packaging.json').as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
