// GENERATED by tools/gen_package.py — thumbnail shot.
import React from 'react';
import { ThumbnailCard, type ThumbProps } from '../../lib/thumbnail';

export const compositionConfig = { id: 'ThumbWorldmonitor0', durationInSeconds: 1, fps: 30, width: 1280, height: 720 };

const PROPS = ({"overlay": "ONE AI DASHBOARD", "name": "worldmonitor", "owner": "koala73", "stars": 68328, "templateId": "editorial", "variant": 0}) as ThumbProps;
const ThumbWorldmonitor0: React.FC = () => <ThumbnailCard {...PROPS} />;
export default ThumbWorldmonitor0;
