// GENERATED by tools/gen_package.py — thumbnail shot.
import React from 'react';
import { ThumbnailCard, type ThumbProps } from '../../lib/thumbnail';

export const compositionConfig = { id: 'ThumbWorldmonitor1', durationInSeconds: 1, fps: 30, width: 1280, height: 720 };

const PROPS = ({"overlay": "NO MORE TABS", "name": "worldmonitor", "owner": "koala73", "stars": 68328, "templateId": "editorial", "variant": 1}) as ThumbProps;
const ThumbWorldmonitor1: React.FC = () => <ThumbnailCard {...PROPS} />;
export default ThumbWorldmonitor1;
