// GENERATED by tools/gen_faceless.py — do not edit by hand.
// Edit <project>/work/storyboard.json and re-run with --from-storyboard.
import React from 'react';
import { StoryboardVideo, type Scene } from '../../lib/storyboard';

export const compositionConfig = { id: 'SrcRuViewTheAntiCamera', durationInSeconds: 129.2, fps: 30, width: 1920, height: 1080 };

const SCENES = ([
  {
    "type": "title",
    "narration": "What if you could track your sleep, detect falls, and guard your house without placing a single creepy camera indoors?",
    "eyebrow": "The Zero-Optical Guardian",
    "title": "The Anti Camera",
    "subtitle": "Zero pixels. Total spatial awareness.",
    "dur": 265,
    "audio": "projects/ruview/narration/00.mp3"
  },
  {
    "type": "statement",
    "narration": "Indoor optical cameras promise safety, but they compromise your personal privacy inside your sanctuary.",
    "eyebrow": "The Camera Privacy Dilemma",
    "text": "Indoor optical surveillance breaches personal privacy",
    "dur": 231,
    "audio": "projects/ruview/narration/01.mp3"
  },
  {
    "type": "features",
    "narration": "Enter RuView, an open-source system turning standard WiFi signals into real-time spatial intelligence.",
    "eyebrow": "Sensing Without Pixels",
    "items": [
      {
        "label": "WiFi CSI Sensing"
      },
      {
        "label": "Zero Optical Pixels"
      }
    ],
    "dur": 250,
    "audio": "projects/ruview/narration/02.mp3"
  },
  {
    "type": "repo_scroll",
    "narration": "On GitHub, this eighty-three-thousand-star repository provides Rust code, benchmark tests, and dashboard tools.",
    "eyebrow": "GitHub Inspection",
    "repo": {
      "owner": "ruvnet",
      "name": "RuView",
      "url": "https://github.com/ruvnet/RuView",
      "stars": 83938,
      "description": "π RuView turns commodity WiFi signals into real-time spatial intelligence, vital sign monitoring, and presence detection — all without a sin",
      "topics": [
        "Rust",
        "awesome",
        "claude",
        "densepose",
        "esp32",
        "firmware"
      ],
      "files": [
        "CHANGELOG.md",
        "CLAUDE.md",
        "LICENSE",
        "Makefile",
        "PROOF.md",
        "README.md",
        "aether-arena/",
        "archive/",
        "assets/",
        "benchmark_baseline.json",
        "benchmarks/",
        "dashboard/"
      ],
      "readme": [
        "π RuView turns commodity WiFi signals into real-time spatial intelligence, vital sign",
        "monitoring, and presence detection — all without a single pixel of video.",
        "## Features",
        "- See through walls with WiFi",
        "- Built for low-power edge applications",
        "- Pretrained model on Hugging Face",
        "- Results & proof",
        "- Edge Module Catalog",
        "- Health — <sub>14 modules</sub>",
        "## Highlights",
        "- Presence and occupancy — detect people through walls, count them, track entries and exits",
        "- Vital signs — breathing rate and heart rate, contactless, while sleeping or sitting",
        "- Activity recognition — walking, sitting, gestures, falls — from temporal CSI patterns",
        "- Sleep quality — overnight monitoring with sleep stage classification and apnea screening",
        "- Runs on an $8 ESP32 chip the entire model fits in 55 KB of memory",
        "## Built with",
        "Rust, awesome, claude, densepose, esp32, firmware, home-assistant, home-automation"
      ]
    },
    "dur": 249,
    "audio": "projects/ruview/narration/03.mp3"
  },
  {
    "type": "bullets",
    "narration": "Instead of glass lenses, it runs a tiny fifty-five kilobyte model on eight-dollar ESP32 hardware.",
    "eyebrow": "Ultra-Low-Power Edge",
    "points": [
      "$8 ESP32 Chips",
      "55 KB Model Size"
    ],
    "title": "Hardware Efficiency",
    "dur": 243,
    "audio": "projects/ruview/narration/04.mp3"
  },
  {
    "type": "statement",
    "narration": "Camera lenses shatter into wireframe skeletal poses derived purely from radio frequency CSI disruption.",
    "eyebrow": "Hugging Face DensePose Mapping",
    "text": "Lenses shatter into pure wireframe skeletal poses",
    "dur": 248,
    "audio": "projects/ruview/narration/05.mp3"
  },
  {
    "type": "features",
    "narration": "Using pretrained Hugging Face models, radio waves reconstruct human pose geometry without taking images.",
    "eyebrow": "Pretrained Intelligence",
    "items": [
      {
        "label": "Hugging Face Hub"
      },
      {
        "label": "WiFi DensePose AI"
      }
    ],
    "dur": 254,
    "audio": "projects/ruview/narration/06.mp3"
  },
  {
    "type": "bullets",
    "narration": "The system measures vital signs, tracking breathing rate and heart rate contactless while sleeping.",
    "eyebrow": "Sleep Apnea and Fall Detection",
    "points": [
      "Heart & Breathing Rates",
      "Contactless Overnight Monitoring"
    ],
    "title": "Vital Sign Intelligence",
    "dur": 213,
    "audio": "projects/ruview/narration/07.mp3"
  },
  {
    "type": "steps",
    "narration": "It instantly detects physical falls and screens overnight sleep quality using temporal wave patterns.",
    "eyebrow": "Activity Recognition",
    "steps": [
      "Detect Physical Falls",
      "Screen Sleep Apnea"
    ],
    "dur": 216,
    "audio": "projects/ruview/narration/08.mp3"
  },
  {
    "type": "code",
    "narration": "You can run the wifi-densepose container with Docker to launch local spatial sensing endpoints.",
    "eyebrow": "Setting Up Home Assistant Trigge",
    "lines": [
      "docker pull ruvnet/wifi-densepose:latest",
      "docker run -p 3000:3000 ruvnet/wifi-densepose:latest"
    ],
    "filename": "terminal",
    "dur": 199,
    "audio": "projects/ruview/narration/09.mp3"
  },
  {
    "type": "statement",
    "narration": "Provisioning ESP32 microcontrollers over serial creates persistent sensing nodes inside your home.",
    "eyebrow": "Edge Node Provisioning",
    "text": "Flash ESP32-S3 microcontrollers over serial port",
    "dur": 225,
    "audio": "projects/ruview/narration/10.mp3"
  },
  {
    "type": "features",
    "narration": "RuView integrates directly with Home Assistant to fire instant local automation triggers.",
    "eyebrow": "Home Automation",
    "items": [
      {
        "label": "Home Assistant Native"
      },
      {
        "label": "Instant Local Triggers"
      }
    ],
    "dur": 198,
    "audio": "projects/ruview/narration/11.mp3"
  },
  {
    "type": "bullets",
    "narration": "Radio signals pass straight through solid concrete walls, tracking movement, entries, and exits.",
    "eyebrow": "Testing Spatial Detection",
    "points": [
      "Pass Through Concrete",
      "Count & Track Occupants"
    ],
    "title": "Wall Penetration",
    "dur": 209,
    "audio": "projects/ruview/narration/12.mp3"
  },
  {
    "type": "steps",
    "narration": "The Zero-Optical Guardian keeps total spatial awareness across hidden rooms in absolute darkness.",
    "eyebrow": "Zero-Optical Surveillance",
    "steps": [
      "Penetrate Hidden Barriers",
      "Sustain Pitch-Black Vision"
    ],
    "dur": 221,
    "audio": "projects/ruview/narration/13.mp3"
  },
  {
    "type": "statement",
    "narration": "Because zero pixels of video are ever captured or stored, privacy is guaranteed by architecture.",
    "eyebrow": "Absolute Privacy as an Architect",
    "text": "Mathematical privacy with zero recorded frames",
    "dur": 232,
    "audio": "projects/ruview/narration/14.mp3"
  },
  {
    "type": "bullets",
    "narration": "Camera lenses shatter as pure RF physics safeguards your home without exposing your private life.",
    "eyebrow": "Tactical Privacy",
    "points": [
      "Shattered Lens Motif",
      "RF Wave Guardian"
    ],
    "title": "Physics Over Lenses",
    "dur": 214,
    "audio": "projects/ruview/narration/15.mp3"
  },
  {
    "type": "cta",
    "narration": "Explore RuView on GitHub today to build your own zero-optical spatial intelligence network.",
    "eyebrow": "Deploy RuView",
    "title": "Build The Zero-Optical Guardian",
    "sub": "github.com/ruvnet/RuView",
    "dur": 209,
    "audio": "projects/ruview/narration/16.mp3"
  }
]) as unknown as Scene[];

const SrcRuViewTheAntiCamera: React.FC = () => (
  <StoryboardVideo scenes={SCENES} width={1920} height={1080} captions={true} templateId={'concept-the-anti-camera'} />
);
export default SrcRuViewTheAntiCamera;
