// GENERATED by tools/gen_faceless.py — do not edit by hand.
// Edit <project>/work/storyboard.json and re-run with --from-storyboard.
import React from 'react';
import { StoryboardVideo, type Scene } from '../../lib/storyboard';

export const compositionConfig = { id: 'SrcWorldMonitorAIRealTimeIntelligenV', durationInSeconds: 67.233, fps: 30, width: 1080, height: 1920 };

const SCENES = ([
  {
    "type": "title",
    "narration": "Tracking global events in real time usually requires dozens of open tabs and complex tools.",
    "eyebrow": "Open Source AI",
    "title": "World Monitor",
    "subtitle": "Real-Time Global Intelligence Dashboard",
    "dur": 220,
    "audio": "projects/studio/narration/00.mp3"
  },
  {
    "type": "statement",
    "narration": "World Monitor aggregates global news, infrastructure tracking, and geopolitics into one real-time dashboard.",
    "eyebrow": "Overview",
    "text": "Unified situational awareness interface",
    "dur": 256,
    "audio": "projects/studio/narration/01.mp3"
  },
  {
    "type": "repo_scroll",
    "narration": "With over sixty-eight thousand stars on GitHub, the repo features detailed architecture docs and simple setup files.",
    "eyebrow": "on github",
    "repo": {
      "owner": "koala73",
      "name": "worldmonitor",
      "url": "http://github.com/koala73/worldmonitor",
      "stars": 68328,
      "description": "Real-time global intelligence dashboard. AI-powered news aggregation, geopolitical monitoring, and infrastructure tracking in a unified situ",
      "topics": [
        "TypeScript",
        "agent",
        "ai",
        "dashboard",
        "geopolitics",
        "mcp"
      ],
      "files": [
        "AGENTS.md",
        "ARCHITECTURE.md",
        "CHANGELOG.md",
        "CODE_OF_CONDUCT.md",
        "CONCEPTS.md",
        "CONTRIBUTING.md",
        "Dockerfile",
        "Dockerfile.digest-notifications",
        "Dockerfile.publish-bootstrap-tiers",
        "Dockerfile.relay",
        "Dockerfile.seed-bundle-portwatch-port-activity",
        "Dockerfile.seed-bundle-resilience-validation"
      ],
      "readme": [
        "Real-time global intelligence dashboard. AI-powered news aggregation, geopolitical",
        "monitoring, and infrastructure tracking in a unified situational awareness interface",
        "## Features",
        "- What It Does",
        "- Support Status",
        "- Quick Start",
        "- Tech Stack",
        "- Programmatic Access",
        "- Flight Data",
        "## Highlights",
        "- 500+ curated news feeds across 15 categories, AI-synthesized into briefs",
        "- Dual map engine — 3D globe globe.gl and WebGL flat map deck.gl with 56 map layer types",
        "- Cross-stream correlation — military, economic, disaster, and escalation signal convergence",
        "- Finance radar — 29 stock exchanges, commodities, crypto, and 7-signal market composite",
        "- Local AI — run everything with Ollama, no API keys required",
        "## Built with",
        "TypeScript, agent, ai, dashboard, geopolitics, mcp, mcp-server, monitoring"
      ]
    },
    "dur": 272,
    "audio": "projects/studio/narration/02.mp3"
  },
  {
    "type": "features",
    "narration": "It features a dual map engine supporting a 3D globe and fifty-six distinct layer types.",
    "eyebrow": "Visualization",
    "items": [
      {
        "label": "3D Globe (globe.gl)"
      },
      {
        "label": "WebGL Map (deck.gl)"
      },
      {
        "label": "56 Map Layer Types"
      }
    ],
    "dur": 210,
    "audio": "projects/studio/narration/03.mp3"
  },
  {
    "type": "bullets",
    "narration": "Over five hundred news feeds are AI-synthesized into briefs with cross-stream military and economic correlation.",
    "eyebrow": "AI Synthesis",
    "points": [
      "500+ curated news feeds across 15 categories",
      "Cross-stream military and economic signal convergence"
    ],
    "title": "Global News & Signal Correlation",
    "dur": 249,
    "audio": "projects/studio/narration/04.mp3"
  },
  {
    "type": "steps",
    "narration": "You can monitor twenty-nine stock exchanges, commodities, crypto, and a seven-signal market composite.",
    "eyebrow": "Finance Radar",
    "steps": [
      "29 Stock Exchanges",
      "Commodities & Crypto",
      "7-Signal Composite"
    ],
    "dur": 223,
    "audio": "projects/studio/narration/05.mp3"
  },
  {
    "type": "code",
    "narration": "Clone the repository, install dependencies, and launch your local web application in seconds.",
    "eyebrow": "Quick Start",
    "lines": [
      "git clone https://github.com/koala73/worldmonitor.git",
      "cd worldmonitor",
      "npm install",
      "npm run dev"
    ],
    "filename": "terminal",
    "dur": 203,
    "audio": "projects/studio/narration/06.mp3"
  },
  {
    "type": "statement",
    "narration": "You can run the entire intelligence suite locally using Ollama without needing API keys.",
    "eyebrow": "Local AI",
    "text": "Run fully local with Ollama—no API keys required",
    "dur": 193,
    "audio": "projects/studio/narration/07.mp3"
  },
  {
    "type": "cta",
    "narration": "Check out the World Monitor repository today to build your own live intelligence center.",
    "title": "Try World Monitor",
    "sub": "github.com/koala73/worldmonitor",
    "dur": 191,
    "audio": "projects/studio/narration/08.mp3"
  }
]) as unknown as Scene[];

const SrcWorldMonitorAIRealTimeIntelligenV: React.FC = () => (
  <StoryboardVideo scenes={SCENES} width={1080} height={1920} captions={true} templateId={'editorial'} />
);
export default SrcWorldMonitorAIRealTimeIntelligenV;
